name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - name: Set up a PureScript toolchain
        uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "latest"
          # NOTE: "latest" = "0.11.1" and "0.11.1" was removed (?)
          purs-tidy: "0.11.0" # "latest"
          spago: "unstable" # "0.93.43" # "next"

      - name: Cache PureScript dependencies
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/spago.lock') }}
          path: |
            .spago
            output

      - run: spago build --strict --ensure-ranges --pedantic-packages

      - run: spago test --strict --pedantic-packages --offline
